name: Pre-Merge Code Analysis
description: Workflow to implement static code analysis

inputs:
  cf_template_path:
    description: path to the api templae json
    required: true
    default: 'welcome-api.template.json'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install OPA
      shell: bash
      run: |
        chmod +x ./opa
        ./opa version
    - name: cdk synth
      shell: bash
      run: |
        yarn
        yarn cdk synth -q -o .
        ls -l
    - name: evaluate opa
      shell: bash
      run: |
        echo ===
        echo response is $(./opa eval --format pretty -i ${{ inputs.cf_template_path}} -d policy.rego "data" | jq )
        echo ===
        if [[ $(./opa eval --format pretty -i ${{ inputs.cf_template_path}} -d policy.rego "data" | jq .policy.allow) = true ]]; then
        # if [[ $(./opa eval --format pretty -i welcome-api.template.json -d policy.rego "data" | jq .policy.allow) = true ]]; then
          echo "Policy Check Passed"
        else
          echo "Policy Check Failed - Fail Pipeline"
          exit 1
        fi
