name: Pre-Merge Security Steps
description: Workflow to implement static code analysis

inputs:
  cf_folder_path:
    description: Path to cloudformation files
    required: true
  cf_file_path:
    description: order of cloudformation files to process
    required: true
  cf_rules_path:
    description: path to the ruleset file
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cloudformation Deploy
      shell: bash
      run: |
        echo cloudformation will be deployed here
    #     - name: Generate CF File
    #       working-directory: cdk
    #       shell: bash
    #       run: |
    #        yarn
    #        yarn cdk synth -q -o ../configs/cdk
    - name: cloudformation guard
      shell: bash
      run: |
        cat ${{ inputs.cf_folder_path}}/${{ inputs.cf_file_path }}
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
        PATH=$PATH:~/.guard/bin/
        cfn-guard validate -r ${{ cf_rules_path }} -d ${{ inputs.cf_folder_path}}/${{ inputs.cf_file_path }}
